FROM golang:1.6.3
MAINTAINER Sakeven Jiang <sakeven.jiang@daocloud.io>

RUN apt-get update -y && \
	apt-get install -y libgmp-dev 

EXPOSE 80

ADD /root/.local/bin/hadolint $GOPATH/bin/hadolint
ADD server $GOPATH/src/server
RUN go install server

CMD ["server"]
