FROM golang:1.6.3
MAINTAINER Sakeven Jiang <sakeven.jiang@daocloud.io>

RUN apt-get update -y && \
	apt-get install -y --no-install-recommends libgmp-dev=2:6.0.0+dfsg-6 0 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

EXPOSE 8000

COPY /root/.local/bin/hadolint $GOPATH/bin/hadolint
COPY server $GOPATH/src/server
RUN go install server

CMD ["server"]
